export const mockData = [
  {
    full_name: "Alice Johnson",
    first_name: "Alice",
    last_name: "Johnson",
    title: "Marketing Specialist",
    email: "alice.johnson@acmecorp.com",
    linkedin_url: "https://www.linkedin.com/in/alice-johnson/",
    company_name: "Acme Corp",
    company_domain: "acmecorp.com",
    company_description:
      "Global leader in industrial manufacturing and automation solutions",
  },
  {
    full_name: "Bob Lee",
    first_name: "Bob",
    last_name: "Lee",
    title: "CTO",
    email: "bob.lee@example.com",
    linkedin_url: "https://www.linkedin.com/in/bob-lee/",
    company_name: "Techify Inc",
    company_domain: "techify.com",
    company_description: "Innovative tech solutions",
  },
  {
    full_name: "Carol Smith",
    first_name: "Carol",
    last_name: "Smith",
    title: "HR Manager",
    email: "carol.smith@techcorp.com",
    linkedin_url: "https://www.linkedin.com/in/carol-smith/",
    company_name: "TechCorp",
    company_domain: "techcorp.com",
    company_description: "Technology services and digital transformation",
  },
  {
    full_name: "Dan Brown",
    first_name: "Dan",
    last_name: "Brown",
    title: "Product Manager",
    email: "dan.brown@brightwave.co",
    linkedin_url: "https://www.linkedin.com/in/dan-brown-pm/",
    company_name: "BrightWave",
    company_domain: "brightwave.co",
    company_description: "Marketing & advertising agency",
  },
  {
    full_name: "Siddharth Shankar Tripathi",
    first_name: "Siddharth",
    last_name: "Shankar Tripathi",
    title: "Software Engineer",
    email: "siddharth.tripathi@innoworks.in",
    linkedin_url: "https://www.linkedin.com/in/siddharth-tripathi/",
    company_name: "InnoWorks",
    company_domain: "innoworks.in",
    company_description: "AI-driven innovation and software consulting",
  },
  {
    full_name: "Frank Wright",
    first_name: "Frank",
    last_name: "Wright",
    title: "Engineer",
    email: "frank.wright@example.com",
    linkedin_url: "https://www.linkedin.com/in/frank-wright/",
    company_name: "BuildIt LLC",
    company_domain: "buildit.io",
    company_description: "Construction software",
  },
];
